apps/funcionarios/urls.py
from django.urls import path


from apps.funcionarios import views

app_name = 'funcionario'

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('add', views.add, name='add'),
]

gestao_rh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(AbstractUser):
    departamentos = models.ManyToManyField(Departamento, blank=True)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.SET_NULL, null=True, blank=True)

    def set_password(self, password):
        return super().set_password(password)

    def __str__(self) -> str:
        return f'{self.username}'

apps/funcionarios/forms.py
from django import forms

from .models import Funcionario


class FuncionarioForm(forms.ModelForm):

    class Meta:
        model = Funcionario
        fields = (
            "username",
            "password",
            "first_name",
            "last_name",
            "email",
            "departamentos",
            "empresa",
            "is_active",
            "is_superuser",
            "is_staff",
        )

apps/funcionarios/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


from apps.funcionarios.models import Funcionario
from apps.funcionarios.forms import FuncionarioForm
# Create your views here.

def index(request):
    return HttpResponse('Hello World!')


def list(request):
    funcionarios = Funcionario.objects.filter(empresa=request.user.empresa, is_active=True)
    context = {'funcionarios': funcionarios}

    return render(request, 'list.html', context)


def add(request):
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('home'))
    
    context = {
        'form': FuncionarioForm,
    }

    return render(request, 'add.html', context)


@csrf_exempt
def delete(request):
    if request.method == 'POST':
        id_funcionario = request.POST['id_funcionario']
        try: 
            funcionario = Funcionario.objects.get(id=id_funcionario)
            funcionario.is_active = False
            funcionario.save()
            response = {'icon': 'success', 'title': 'Sucesso', 'text': 'Funcionário removido com sucesso!'}
        except Funcionario.DoesNotExist:
            response = {'icon': 'error', 'title': 'Erro', 'text': 'Não foi encontrado o funcionário'}

        return JsonResponse(response, safe=False)

def edit(request, id):
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            funcionario = Funcionario.objects.get(id=id)
            funcionario.username = form.cleaned_data['username']
            
            funcionario.set_password(form.cleaned_data['password'])
            funcionario.first_name = form.cleaned_data['first_name']
            funcionario.last_name = form.cleaned_data['last_name']
            funcionario.email = form.cleaned_data['email']
            funcionario.last_name = form.cleaned_data['last_name']
            funcionario.departamentos.set(form.cleaned_data['departamentos'])
            funcionario.empresa = form.cleaned_data['empresa']
            funcionario.is_active = form.cleaned_data['is_active']
            funcionario.is_superuser = form.cleaned_data['is_superuser']
            funcionario.is_staff = form.cleaned_data['is_staff']

            funcionario.save()

            return redirect(reverse('home'))

    form = FuncionarioForm()

    context = {
        'form': form
    }

    return render(request, 'edit.html', context)

apps/funcionarios/templates/add.html
{% extends 'base.html' %}

{% block title %} Cadastrar Funcionário {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
    <h1 class="text-center mt-5">Formulário: Cadastrar funcionário</h1>

<div class="d-flex justify-content-center mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark">Cadastrar Funcionário</button>
    </form>
</div>


{% endblock main %}

apps/funcionarios/templates/edit.html
{% extends 'base.html' %}

{% block title %} Editar Funcionário {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
    <h1 class="text-center mt-5">Formulário: Editar de funcionário</h1>

<div class="d-flex justify-content-center mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark">Editar Funcionário</button>
    </form>
</div>


{% endblock main %}

apps/funcionarios/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Listar Funcionarios {% endblock title %}
{% block navbar %} {% include 'partials/navbar.html' %} {% endblock  %}

{% block main %}
<div class="card mt-5 ">
  <div class="card-header text-center">
    Listagem de funcionários
  </div>
  <div class="card-body">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Primeiro Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
        {% for funcionario in funcionarios  %}
            <tr>
                <th scope="row">{{ funcionario.id }}</th>
                <td>{{ funcionario.first_name }}</td>
                <td>{{ funcionario.last_name }}</td>
                <td>{{ funcionario.email }}</td>
                <td>
                  <a href="{% url 'funcionario:edit' funcionario.id %}" class="btn btn-outline-dark">
                    <span class="material-icons">edit</span>
                  </a>

                  <button id="{{ funcionario.id }}" class="btn btn-outline-danger remove_funcionario">
                    <span class="material-icons">delete</span>
                  </button>
                
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
</div>
{% endblock main %}

{% block script %}

  <script src="{% static 'js/apps/funcionarios.js' %}" type="text/javascript"></script>

{% endblock  %}