apps/departamentos/urls.py
from django.urls import path

from apps.departamentos import views

app_name = 'departamento'

urlpatterns = [
    path('list', views.list, name='list'),
    # path('edit/<int:id>', views.edit, name='edit'),
    # path('delete', views.delete, name='delete'),
    # path('add', views.add, name='add'),
]

apps/empresas/urls.py
from django.urls import path


from apps.empresas import views

app_name='empresa'

urlpatterns = [
    path('create', views.create, name='create'),
    path('edit/<int:id>', views.edit, name='edit'),
]

apps/funcionarios/urls.py
from django.urls import path


from apps.funcionarios import views

app_name = 'funcionario'

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete', views.delete, name='delete'),
    path('add', views.add, name='add'),
]

gestao_rh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar scroll</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Funcionários</a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{% url 'funcionario:list' %}">Listar Funcionários</a></li>
            <li><a class="dropdown-item" href="{% url 'funcionario:add' %}">Adicionar Funcionário</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ request.user.empresa.nome }}</a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{% url 'empresa:edit' request.user.empresa.id %}">Editar Empresa</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="{% url 'departamento:list'  %}">Departamentos</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav  my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {% if request.user %}
            {{request.user.first_name}}
          {% else %}
            Login
          {% endif %}
            </a>
          {% if request.user %}
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#">Nada</a></li>  
          </ul>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>